version: 2
sources:
    - name: datafeed_shared_schema
      database: "{{('sales')}}"
      schema: staging_layer
      tables:
        - name: stg_customers
        - name: stg_payments
        - name: stg_orders
        - name: STG_ITEMS_DATA
        - name: STG_PRODUCT_DATA
        - name: STG_SUPPLIES_DATA
